//convert presets to array in order to preserve order

export default [
  {
    name: "Normal",
    contrast: 100,
    brightness: 100,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 0,
    opacity: 100,
    saturate: 100,
    sepia: 0,
    red: 255,
    green: 255,
    blue: 255,
    colorOpacity: 0,
    mode: "overlay"
  },
  {
    name: "1977",
    contrast: 110,
    brightness: 110,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 0,
    opacity: 100,
    saturate: 130,
    sepia: 0,
    red: 243,
    green: 106,
    blue: 188,
    colorOpacity: 3,
    mode: "screen"
  },
  {
    name: "Aden",
    contrast: 90,
    brightness: 120,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 20,
    opacity: 100,
    saturate: 85,
    sepia: 0,
    red: 66,
    green: 10,
    blue: 14,
    colorOpacity: 2,
    mode: "darken"
  },
  {
    name: "Amaro",
    contrast: 90,
    brightness: 110,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 350,
    opacity: 100,
    saturate: 150,
    sepia: 0,
    red: 255,
    green: 255,
    blue: 255,
    colorOpacity: 0,
    mode: "overlay"
  },
  {
    name: "Brannan",
    contrast: 140,
    brightness: 100,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 0,
    opacity: 100,
    saturate: 100,
    sepia: 50,
    red: 161,
    green: 44,
    blue: 199,
    colorOpacity: 3,
    mode: "lighten"
  },
  {
    name: "Clarendon",
    contrast: 120,
    brightness: 100,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 0,
    opacity: 100,
    saturate: 125,
    sepia: 0,
    red: 127,
    green: 187,
    blue: 227,
    colorOpacity: 2,
    mode: "overlay"
  },
  {
    name: "Inkwell",
    contrast: 110,
    brightness: 110,
    grayscale: 100,
    invert: 0,
    blur: 0,
    hueRotate: 0,
    opacity: 100,
    saturate: 100,
    sepia: 30,
    red: 255,
    green: 255,
    blue: 255,
    colorOpacity: 0,
    mode: "overlay"
  },
  {
    name: "Toaster",
    contrast: 150,
    brightness: 90,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 0,
    opacity: 100,
    saturate: 100,
    sepia: 0,
    red: 59,
    green: 0,
    blue: 59,
    colorOpacity: 5,
    mode: "screen"
  },
  {
    name: "Walden",
    contrast: 100,
    brightness: 110,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 350,
    opacity: 100,
    saturate: 160,
    sepia: 30,
    red: 204,
    green: 68,
    blue: 0,
    colorOpacity: 3,
    mode: "screen"
  },
  {
    name: "Xpro2",
    contrast: 100,
    brightness: 100,
    grayscale: 0,
    invert: 0,
    blur: 0,
    hueRotate: 0,
    opacity: 100,
    saturate: 100,
    sepia: 30,
    red: 43,
    green: 42,
    blue: 161,
    colorOpacity: 0,
    mode: "color-burn"
  }
];
